## Discounted Cash Flow

### 1. Estimate Free Cash Flows for Each Year

* BYFCF - Base Year Free Cash Flow
* $FCF_n$ - Free cash flow for year $n$
* $n$ - the number of years into the future
* $GR$ - the company's estimated annual growth rate

$$
FCF_n = BYFCF*(1 + GR)^n
$$

### 2. Estimate the Discount Factor for Each Year

$$
DF_n = (1+DR)^n
$$

* $DF_n$ - The discount factor during year n
* $DR$ - Discount rate
* $n$ - Year being discounted

### 3. Calculate the Discount Value of FCF for N=10 Years

$$
DFCF_n = \frac{FCF_n}{DF_n} = BYFCF \left( \frac{1+GR}{1+DR} \right)
$$

* $DFCF_n$ - Discounted free cash flow for year $n$
* $FCF_n$ - Free cash flow for year $n$
* $GR$ - Estimated annual growth rate
* $DR$ - Discount rate

### Calculate the Discounted Perpetuity Free Cash Flow (beyond ten years)

$$
DPCF = BYFCF \frac{(1 + GR)^{N+1}(1+LGR)}{DR - LGR} \frac{1}{(1+DR)^{N+1}}
$$
* $DPCF$ - Discounted perpetuity cash flow
* $BYFCF$ - Base year free cash flow
* $GR$ - Growth rate of FCF
* $DR$ - Discount rate
* $LGR$ - Long-term growth rate

$$
S_n = 1 + q + ... + q^n = \frac{1-q^n}{1-q}
$$

$$
S = lim_{n \to \inf} S_n = \frac{1}{1-q}
$$

$$
PCF_n = FCF_N*(1+LGR)^n
$$

$$
DPCF_n = \frac{DFCF_N(1+LGR)^n}{(1+DR)^n} = FCF_N \left( \frac{1+LGR}{1+DR} \right)^n
$$

$$
\begin{align}
DPCF & = \sum_{n=1}^{\inf} DPCF_n   \\
  & = DFCF_N \sum_{n=1}^{\inf} \left( \frac{1+LGR}{1+DR} \right)^n  \\
  & = DFCF_N \frac{1}{1 - \frac{1+LGR}{1+DR}}  \\
  & = BYCF \frac{1+DR}{DR-LGR} \left( \frac{1+GR}{1+DR}  \right)^{N+1}
\end{align}
$$

In [1]:
import numpy as np
import pandas as pd

In [3]:
GR = 0.06
BYCF = 1000
DR = 0.1
LGR = 0.03
N = 10

DPCF = BYCF*(1+DR)/(DR-LGR)*((1+GR)/(1+DR))**(N+1)

In [4]:
DPCF

10455.37529285682

In [14]:
FCF = BYCF*(1+GR)**np.arange(10)
FCF

array([1000.        , 1060.        , 1123.6       , 1191.016     ,
       1262.47696   , 1338.2255776 , 1418.51911226, 1503.63025899,
       1593.84807453, 1689.478959  ])

In [15]:
DFCF = FCF/(1+DR)**np.arange(10)

In [16]:
DFCF

array([1000.        ,  963.63636364,  928.59504132,  894.82794891,
        862.28875077,  830.93279619,  800.71705815,  771.60007422,
        743.5418897 ,  716.5040028 ])

In [17]:
DFCF.sum()

np.float64(8512.64392570813)

In [18]:
DFCF.sum() + DPCF

np.float64(18968.01921856495)

## The Combined DCF Formula

The total value ($V_0$) is expressed as:
$$
V_0 = \sum_{t=1}^{n} \frac{FCF_t}{(1+r)^t} + \frac{TV_n}{(1+r)^n}
$$

Where the **Terminal Value** ($TV_n) at the end of the forecast period ($n$) is calculated using the perpetual growth method (Gordon Growth Model):

$$
TV_n = \frac{FCF_n \times (1+g)}{r-g} = \frac{FCF_{n+1}}{r-g}
$$

**Key Variables:**
* $FCF_t$: Free cash flow in explicit period $t$.
* $FCF_n$: Free cash flow in the final forecasted year.
* $FCF_{n+1}$: Projected free cash flow for the first year beyond the forecast period ($FCF_n\times (1+g)$).
* $r$: Discount rate, typically the Weighted Average Cost of Capital (WACC).
* $g$: Perpetual growth rate of the cash flows beyound year $n$.
* $n$: Number of explicit forecast periods (years).

In [29]:
g = 2.5/100
r = 10.0/100
FCF_0 = 30.0
GR = 15.0/100
n=10

In [39]:
# Free Cash Flows
FCF_t = FCF_0*(1+GR)**np.arange(1,n+1)
FCF_t

array([ 34.5       ,  39.675     ,  45.62625   ,  52.4701875 ,
        60.34071562,  69.39182297,  79.80059641,  91.77068588,
       105.53628876, 121.36673207])

In [34]:
# Discounted Free Cash Flows
DFCF_t = FCF_t/(1+r)**np.arange(1,n+1)
DFCF_t

array([31.36363636, 32.7892562 , 34.27967693, 35.83784407, 37.46683698,
       39.16987502, 40.95032389, 42.81170225, 44.75768871, 46.79212911])

In [35]:
# Terminal Value
TV = FCF_t[-1]*(1+g)/(r-g)
TV

np.float64(1658.6786716402414)

In [36]:
# Discounted Terminal Value
DTV = TV/(1+r)**n
DTV

np.float64(639.4924311707842)

In [38]:
# Value
V_0 = DFCF_t.sum() + DTV
V_0

np.float64(1025.711400702106)

In [187]:
import numpy as np

def period_indexes(n) -> np.ndarray:
    """Returns array of period indexes: 1, 2, 3,..."""
    return np.arange(1, n+1)

def discounted(values, discount_rate) -> np.ndarray:
    """
    Calculate discounted present value using: Discounted_t = Value_t / (1 + discount_rate)^t
    """
    # https://medium.com/@gianlucabaglini/automate-your-discounted-cash-flow-model-in-python-cdf98eb0924d
    period_indexes = np.arange(1, len(values)+1)
    discounted_values = values/(1 + discount_rate)**period_indexes
    return discounted_values
    
def grow_by_rate(initial, rate, num_iterations):
    """Grow a metric by given rate for given number of iterations"""
    return initial*(1+rate)**np.arange(1, num_iterations+1)

def grow_by(initial, growth, num_iterations):
    """Grow a metric by adding a growth at each iteration"""
    return initial + growth*np.arange(1, num_iterations+1)

def total_value_growth_in_perpetuity(free_cash_flows, perpetual_growth_rate, discount_rate, *, output_as="number"):
    n = len(free_cash_flows)
    # Convert to np.array
    fcf_n = np.array(free_cash_flows)
    # discounted free cash flows
    dfcf_n = discounted(fcf_n, discount_rate)
    # discounted free cash flow for all years
    dfcf = dfcf_n.sum()
    # terminal value
    tv = fcf_n[-1]*(1+perpetual_growth_rate)/(discount_rate - perpetual_growth_rate)
    # discounted terminal value
    dtv = tv / (1+discount_rate)**n
    total_value = dfcf + dtv
    match output_as:
        case "number":
            return total_value
        case "dict":
            return {
                "Long-term growth rate": perpetual_growth_rate,
                "Discount rate": discount_rate,
                "Number of years": n,
                "Free Cash Flows": free_cash_flows,
                "Discounted Free Cash Flows": dfcf_n,
                "Total Discounted Free Cash Flow": dfcf,
                "Terminal Value at last year": tv,
                "Discounted Terminal Value": dtv,
                "Total Value": total_value
            }
        case _:
            raise ValueError("Unknown value for output_as. Allowed values: number, dict")

In [188]:
fcf_n = grow_by_rate(30.0, 0.06, 10)
fcf_n

array([31.8       , 33.708     , 35.73048   , 37.8743088 , 40.14676733,
       42.55557337, 45.10890777, 47.81544224, 50.68436877, 53.7254309 ])

In [189]:
tv = total_value_growth_in_perpetuity(fcf_n, 0.025, 0.10, output_as="dict")
tv

{'Long-term growth rate': 0.025,
 'Discount rate': 0.1,
 'Number of years': 10,
 'Free Cash Flows': array([31.8       , 33.708     , 35.73048   , 37.8743088 , 40.14676733,
        42.55557337, 45.10890777, 47.81544224, 50.68436877, 53.7254309 ]),
 'Discounted Free Cash Flows': array([28.90909091, 27.85785124, 26.84483847, 25.86866252, 24.92798389,
        24.02151174, 23.14800223, 22.30625669, 21.49512008, 20.71347935]),
 'Total Discounted Free Cash Flow': np.float64(246.09279712501683),
 'Terminal Value at last year': np.float64(734.2475555825703),
 'Discounted Terminal Value': np.float64(283.08421783489683),
 'Total Value': np.float64(529.1770149599137)}

### Example

Based on https://www.wallstreetprep.com/knowledge/terminal-value/

In this example we assume that free cash flow grows linear with EBITDA. EBITDA grows linearly by fixed amount, e.g. $2mm.

In [190]:
EBITDA_0 = 50  # millions, mm
EBITDA_growth = 2 # millions, mm
FCF_0 = 30   # millions, mm
n = 5 # years
ebitda_conversion_ratio = FCF_0 / EBITDA_0

r = 10.0/100.0 # discount rate
g = 2.5/100.0 # long-term growth rate



In [191]:
years = np.arange(1, n+1)
years

array([1, 2, 3, 4, 5])

In [192]:
# EBITDA for each year grows from the previous year by EBITDA_growth
EBITDA_t = EBITDA_0 + years*EBITDA_growth
EBITDA_t

array([52, 54, 56, 58, 60])

In [193]:
# Free Cash Flow can be obtained from EBITDA by multiplying to the conversion ratio
FCF_t = EBITDA_t * ebitda_conversion_ratio
FCF_t

array([31.2, 32.4, 33.6, 34.8, 36. ])

In [194]:
# Can use `grow_by()` function for the future EBITDA values
grow_by(EBITDA_0, EBITDA_growth, n)*ebitda_conversion_ratio

array([31.2, 32.4, 33.6, 34.8, 36. ])

In [195]:
# Alternatively we could calculate FCF growth from EBITDA growth
FCF_growth = EBITDA_growth*FCF_0/EBITDA_0
FCF_0 + FCF_growth*years

array([31.2, 32.4, 33.6, 34.8, 36. ])

In [196]:
# Total Value in millions, mm
tv = total_value_growth_in_perpetuity(FCF_t, g, r, output_as="dict")
tv

{'Long-term growth rate': 0.025,
 'Discount rate': 0.1,
 'Number of years': 5,
 'Free Cash Flows': array([31.2, 32.4, 33.6, 34.8, 36. ]),
 'Discounted Free Cash Flows': array([28.36363636, 26.7768595 , 25.24417731, 23.76886825, 22.35316763]),
 'Total Discounted Free Cash Flow': np.float64(126.50670905489562),
 'Terminal Value at last year': np.float64(491.9999999999999),
 'Discounted Terminal Value': np.float64(305.49329094510415),
 'Total Value': np.float64(431.9999999999998)}

In [197]:
np.round(tv['Total Value'])

np.float64(432.0)

#### Free Cash Flow growing by rate

In [159]:
FCF_t = grow_by_rate(FCF_0, EBITDA_growth/EBITDA_0, n)
FCF_t

array([31.2       , 32.448     , 33.74592   , 35.0957568 , 36.49958707])

In [160]:
tv = total_value_growth_in_perpetuity(FCF_t, g, r, output_as="dict")
tv

{'Long-term growth rate': 0.025,
 'Discount rate': 0.1,
 'Number of years': 5,
 'Free Cash Flows': array([31.2       , 32.448     , 33.74592   , 35.0957568 , 36.49958707]),
 'Discount Factors': array([1.1    , 1.21   , 1.331  , 1.4641 , 1.61051]),
 'Discounted Free Cash Flows': array([28.36363636, 26.81652893, 25.35380917, 23.97087412, 22.6633719 ]),
 'Total Discounted Free Cash Flow': np.float64(127.168220471776),
 'Terminal Value at last year': np.float64(498.82768998399996),
 'Discounted Terminal Value': np.float64(309.7327492434072),
 'Total Value': np.float64(436.90096971518324)}

In [153]:
np.round(tv['Total Value'])

np.float64(437.0)

In [186]:
x = discounted(FCF_t, 0.025)
x

array([30.43902439, 30.88447353, 31.33644143, 31.7950235 , 32.26031653])

## Resources
* https://www.reddit.com/r/Python/comments/16o183i/discounted_cash_flow_model_in_python_with_monte/
  * https://colab.research.google.com/drive/1XtCNkpbfSoiMXpypcJ3DOzXBZy4jRzn_?usp=sharing#scrollTo=BsAVIq8Id6qt
  * https://github.com/farbodbahari/Business-Valuation-with-Discounted-Cash-Flow-In-Python/blob/main/DCF_Model_Python.ipynb
  * https://youtube.com/playlist?list=PLHSKzVSgP0i1ZwkyrZBQdtC_g6kYVWoe6&si=7LhhoN6jYbQB2wMh
* [Everything Is a DCF Model](https://www.morganstanley.com/content/dam/im/assets/publication/thought-leadership/consilient-observer/article_everythingisadcfmodel_us.pdf?1788543896597) - PDF